"""add question and review_queue tables

Revision ID: c1d831ffba6d
Revises: 71e981f00605
Create Date: 2025-11-08 14:58:14.539251

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'c1d831ffba6d'
down_revision: Union[str, Sequence[str], None] = '71e981f00605'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('review_queue',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('candidate_question_json', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_review_queue_status'), 'review_queue', ['status'], unique=False)
    op.create_table('questions_meta',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('text', sa.Text(), nullable=False),
    sa.Column('domain', sa.String(), nullable=False),
    sa.Column('difficulty', sa.Integer(), nullable=False),
    sa.Column('ideal_answer_snippet', sa.Text(), nullable=True),
    sa.Column('rubric_id', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('promoted_by_admin_id', sa.UUID(), nullable=True),
    sa.ForeignKeyConstraint(['promoted_by_admin_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_questions_meta_domain'), 'questions_meta', ['domain'], unique=False)
    op.create_index(op.f('ix_questions_meta_rubric_id'), 'questions_meta', ['rubric_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_questions_meta_rubric_id'), table_name='questions_meta')
    op.drop_index(op.f('ix_questions_meta_domain'), table_name='questions_meta')
    op.drop_table('questions_meta')
    op.drop_index(op.f('ix_review_queue_status'), table_name='review_queue')
    op.drop_table('review_queue')
    # ### end Alembic commands ###
