"""Change Question ID from UUID to String

Revision ID: d1a38111e117
Revises: 91972c78916e
Create Date: 2025-11-09 15:25:18.804246

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd1a38111e117'
down_revision: Union[str, Sequence[str], None] = '91972c78916e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('questions_meta', 'id',
               existing_type=sa.UUID(),
               type_=sa.String(length=64),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('questions_meta', 'id',
               existing_type=sa.String(length=64),
               type_=sa.UUID(),
               existing_nullable=False)
    # ### end Alembic commands ###
